"use client"; // this is a client component
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from 'next-themes'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Saraf Nawar👋🏽',
  description: 'Generated by create next app',
 }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>  
      <ThemeProvider enableSystem={true} attribute="class">
          <Navbar />
        {children}
        </ThemeProvider></body>
    </html>
  )
}
